//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbRates
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CbRatesDatabaseEntities : DbContext
    {
        public CbRatesDatabaseEntities()
            : base("name=CbRatesDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CurrencyRates> CurrencyRates { get; set; }
    
        public virtual ObjectResult<GetLatestRates_Result> GetLatestRates()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLatestRates_Result>("GetLatestRates");
        }
    }
}
