//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbRates.RatesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceCurrencyRate", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ServiceCurrencyRate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FaceValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IsoCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FaceValue {
            get {
                return this.FaceValueField;
            }
            set {
                if ((this.FaceValueField.Equals(value) != true)) {
                    this.FaceValueField = value;
                    this.RaisePropertyChanged("FaceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IsoCode {
            get {
                return this.IsoCodeField;
            }
            set {
                if ((this.IsoCodeField.Equals(value) != true)) {
                    this.IsoCodeField = value;
                    this.RaisePropertyChanged("IsoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringCode {
            get {
                return this.StringCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StringCodeField, value) != true)) {
                    this.StringCodeField = value;
                    this.RaisePropertyChanged("StringCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RatesService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCurrencyRates", ReplyAction="http://tempuri.org/IService/GetCurrencyRatesResponse")]
        CbRates.RatesService.ServiceCurrencyRate[] GetCurrencyRates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCurrencyRates", ReplyAction="http://tempuri.org/IService/GetCurrencyRatesResponse")]
        System.Threading.Tasks.Task<CbRates.RatesService.ServiceCurrencyRate[]> GetCurrencyRatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCurrencyRatesByDate", ReplyAction="http://tempuri.org/IService/GetCurrencyRatesByDateResponse")]
        CbRates.RatesService.ServiceCurrencyRate[] GetCurrencyRatesByDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCurrencyRatesByDate", ReplyAction="http://tempuri.org/IService/GetCurrencyRatesByDateResponse")]
        System.Threading.Tasks.Task<CbRates.RatesService.ServiceCurrencyRate[]> GetCurrencyRatesByDateAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CbRates.RatesService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CbRates.RatesService.IService>, CbRates.RatesService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CbRates.RatesService.ServiceCurrencyRate[] GetCurrencyRates() {
            return base.Channel.GetCurrencyRates();
        }
        
        public System.Threading.Tasks.Task<CbRates.RatesService.ServiceCurrencyRate[]> GetCurrencyRatesAsync() {
            return base.Channel.GetCurrencyRatesAsync();
        }
        
        public CbRates.RatesService.ServiceCurrencyRate[] GetCurrencyRatesByDate(System.DateTime date) {
            return base.Channel.GetCurrencyRatesByDate(date);
        }
        
        public System.Threading.Tasks.Task<CbRates.RatesService.ServiceCurrencyRate[]> GetCurrencyRatesByDateAsync(System.DateTime date) {
            return base.Channel.GetCurrencyRatesByDateAsync(date);
        }
    }
}
